[agent]
name = "EmailSender"
version = "0.0.1"
description = "EmailSender knows how to send emails using Gmail API"


[options.TIMEOUT_MS]
type = "string"
description = "Connection/tool timeouts in ms"
default = "60000"

[runtimes.executable]
command = ["bash", "-c", "./run_agent.sh main.py"]