[agent]
name = "OrchestratorAgent"
version = "0.0.1"
description = "Coordinates data flow among input, stock fetch, and email send; handles retries and logging."


[options.TIMEOUT_MS]
type = "string"
description = "Connection/tool timeouts in ms"
default = "60000"

[runtimes.executable]
command = ["bash", "-c", "./run_agent.sh main.py"]