[agent]
name = "SlackReader"
version = "0.0.1"
description = "SlackReader identifies itself as a Slack message reader that fetches latest messages from channels or DMs and emits structured events for downstream processing"


[options.TIMEOUT_MS]
type = "string"
description = "Connection/tool timeouts in ms"
default = "60000"

[runtimes.executable]
command = ["bash", "-c", "./run_agent.sh main.py"]