[agent]
name = "StockInfoAgent"
version = "0.0.1"
description = "Fetches current stock price/summary for a ticker using Google Finance API."


[options.TIMEOUT_MS]
type = "string"
description = "Connection/tool timeouts in ms"
default = "60000"

[runtimes.executable]
command = ["bash", "-c", "./run_agent.sh main.py"]