[agent]
name = "EmailSenderAgent"
version = "0.0.1"
description = "Sends stock information via email using Gmail API to recipient_email."


[options.TIMEOUT_MS]
type = "string"
description = "Connection/tool timeouts in ms"
default = "60000"

[runtimes.executable]
command = ["bash", "-c", "./run_agent.sh main.py"]