name: Prettier

on: [push]

jobs:
  prettier:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend # 👈 run all commands inside /frontend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json # or yarn.lock

      - run: npm ci

      - name: Run Prettier check
        run: npm run format:check
